// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 启动 Univer 静态服务器，返回 "http://127.0.0.1:PORT"（失败返回空串）。
Future<String> kbStartUniverServer() =>
    RustLib.instance.api.crateApiKbApiKbStartUniverServer();

/// 文件树（root 为空 = 数据目录根），返回 JSON 字符串。
Future<String> kbFilesTreeJson({required String dataDir, String? root}) =>
    RustLib.instance.api.crateApiKbApiKbFilesTreeJson(
      dataDir: dataDir,
      root: root,
    );

/// 读取文本文件（md/txt）。
Future<String> kbReadText({required String dataDir, required String path}) =>
    RustLib.instance.api.crateApiKbApiKbReadText(dataDir: dataDir, path: path);

/// 写入文本文件。
Future<String> kbWriteText({
  required String dataDir,
  required String path,
  required String content,
}) => RustLib.instance.api.crateApiKbApiKbWriteText(
  dataDir: dataDir,
  path: path,
  content: content,
);

/// 读取 xlsx（base64）。
Future<String> kbReadXlsx({required String dataDir, required String path}) =>
    RustLib.instance.api.crateApiKbApiKbReadXlsx(dataDir: dataDir, path: path);

/// 写入 xlsx（base64），返回 "ok" 或错误信息。
Future<String> kbWriteXlsx({
  required String dataDir,
  required String path,
  required String base64,
}) => RustLib.instance.api.crateApiKbApiKbWriteXlsx(
  dataDir: dataDir,
  path: path,
  base64: base64,
);

/// 创建文件/文件夹（path 以 / 结尾 = 目录）。
Future<String> kbFileCreate({
  required String dataDir,
  required String path,
  String? content,
}) => RustLib.instance.api.crateApiKbApiKbFileCreate(
  dataDir: dataDir,
  path: path,
  content: content,
);

/// 删除文件/文件夹（递归）。
Future<String> kbFileDelete({required String dataDir, required String path}) =>
    RustLib.instance.api.crateApiKbApiKbFileDelete(
      dataDir: dataDir,
      path: path,
    );

/// 执行增量索引，返回 stats JSON。
Future<String> kbIndex({required String dataDir, required bool rebuild}) =>
    RustLib.instance.api.crateApiKbApiKbIndex(
      dataDir: dataDir,
      rebuild: rebuild,
    );

/// RAG 问答，返回 JSON {ok, answer, error_message, references_json}。
Future<String> kbAsk({
  required String dataDir,
  required String query,
  int? k,
  String? path,
  required String embedBaseUrl,
  required String embedApiKey,
  required String embedModel,
  int? embedDim,
  required String answer,
}) => RustLib.instance.api.crateApiKbApiKbAsk(
  dataDir: dataDir,
  query: query,
  k: k,
  path: path,
  embedBaseUrl: embedBaseUrl,
  embedApiKey: embedApiKey,
  embedModel: embedModel,
  embedDim: embedDim,
  answer: answer,
);

/// 精确值检索（Excel 单号/金额），返回 JSON。
Future<String> kbSheets({
  required String dataDir,
  required String q,
  String? path,
  int? topN,
}) => RustLib.instance.api.crateApiKbApiKbSheets(
  dataDir: dataDir,
  q: q,
  path: path,
  topN: topN,
);
