// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../note_image_cleanup.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<NoteImageCleanupScanResult> scanNoteImages({
  required String dataDirectory,
}) => RustLib.instance.api.crateApiNoteImageCleanupApiScanNoteImages(
  dataDirectory: dataDirectory,
);

Future<NoteImageCleanupDeleteResult> deleteUnusedNoteImages({
  required String dataDirectory,
  required List<String> candidateRelativePaths,
}) => RustLib.instance.api.crateApiNoteImageCleanupApiDeleteUnusedNoteImages(
  dataDirectory: dataDirectory,
  candidateRelativePaths: candidateRelativePaths,
);
