// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class NoteImageCleanupDeleteResult {
  final bool ok;
  final String errorMessage;
  final List<NoteImageCleanupEntry> deletedImages;
  final List<NoteImageCleanupEntry> failedImages;
  final int skippedCount;

  const NoteImageCleanupDeleteResult({
    required this.ok,
    required this.errorMessage,
    required this.deletedImages,
    required this.failedImages,
    required this.skippedCount,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      errorMessage.hashCode ^
      deletedImages.hashCode ^
      failedImages.hashCode ^
      skippedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteImageCleanupDeleteResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          errorMessage == other.errorMessage &&
          deletedImages == other.deletedImages &&
          failedImages == other.failedImages &&
          skippedCount == other.skippedCount;
}

class NoteImageCleanupEntry {
  final String relativePath;
  final PlatformInt64 sizeBytes;

  const NoteImageCleanupEntry({
    required this.relativePath,
    required this.sizeBytes,
  });

  @override
  int get hashCode => relativePath.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteImageCleanupEntry &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          sizeBytes == other.sizeBytes;
}

class NoteImageCleanupScanResult {
  final bool ok;
  final String errorMessage;
  final int totalImageCount;
  final int referencedImageCount;
  final PlatformInt64 totalSizeBytes;
  final List<NoteImageCleanupEntry> unusedImages;

  const NoteImageCleanupScanResult({
    required this.ok,
    required this.errorMessage,
    required this.totalImageCount,
    required this.referencedImageCount,
    required this.totalSizeBytes,
    required this.unusedImages,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      errorMessage.hashCode ^
      totalImageCount.hashCode ^
      referencedImageCount.hashCode ^
      totalSizeBytes.hashCode ^
      unusedImages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteImageCleanupScanResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          errorMessage == other.errorMessage &&
          totalImageCount == other.totalImageCount &&
          referencedImageCount == other.referencedImageCount &&
          totalSizeBytes == other.totalSizeBytes &&
          unusedImages == other.unusedImages;
}
