// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'ai.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RegenerateReportRequest {
  final String appDataDir;
  final AiProvider provider;
  final AiModel model;
  final String kind;
  final String targetPath;
  final String dailyNotesDirectory;
  final String weeklyNotesDirectory;
  final String industry;
  final String dailyMergePrompt;
  final String weeklyReportPrompt;
  final String language;
  final bool apiLogEnabled;

  const RegenerateReportRequest({
    required this.appDataDir,
    required this.provider,
    required this.model,
    required this.kind,
    required this.targetPath,
    required this.dailyNotesDirectory,
    required this.weeklyNotesDirectory,
    required this.industry,
    required this.dailyMergePrompt,
    required this.weeklyReportPrompt,
    required this.language,
    required this.apiLogEnabled,
  });

  @override
  int get hashCode =>
      appDataDir.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      kind.hashCode ^
      targetPath.hashCode ^
      dailyNotesDirectory.hashCode ^
      weeklyNotesDirectory.hashCode ^
      industry.hashCode ^
      dailyMergePrompt.hashCode ^
      weeklyReportPrompt.hashCode ^
      language.hashCode ^
      apiLogEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegenerateReportRequest &&
          runtimeType == other.runtimeType &&
          appDataDir == other.appDataDir &&
          provider == other.provider &&
          model == other.model &&
          kind == other.kind &&
          targetPath == other.targetPath &&
          dailyNotesDirectory == other.dailyNotesDirectory &&
          weeklyNotesDirectory == other.weeklyNotesDirectory &&
          industry == other.industry &&
          dailyMergePrompt == other.dailyMergePrompt &&
          weeklyReportPrompt == other.weeklyReportPrompt &&
          language == other.language &&
          apiLogEnabled == other.apiLogEnabled;
}

class RegenerateReportResult {
  final bool ok;
  final String path;
  final String errorCode;
  final String errorMessage;

  const RegenerateReportResult({
    required this.ok,
    required this.path,
    required this.errorCode,
    required this.errorMessage,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ path.hashCode ^ errorCode.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegenerateReportResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          path == other.path &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage;
}
